name: data8
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  path: ^1.8.0
  drift: ^2.5.0
  event: ^2.1.2
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  drift_dev: ^2.5.1
  build_runner: ^2.3.3
